### PR TITLE
[ADD] Unit price in product

### PR DESCRIPTION
**Pull request by quentinDupont**
Simple change for unit price in product view

To be completed with https://github.com/grap/grap-odoo-business/pull/33

### CODE REVIEW

**Comment by legalsylvain** [comment]
see grap/grap-odoo-business#33 comment.

**Comment by quentinDupont** [comment]
> see [grap/grap-odoo-business#33](https://github.com/grap/grap-odoo-business/pull/33) comment.

answered : https://github.com/grap/grap-odoo-business/pull/33#issuecomment-713617313

**Comment by legalsylvain** [comment]
travis pète parce que l'autre branch est pas mergé encore.

**Comment by legalsylvain** [comment]
ça devrait passer.

**Pull request merged**
